[tool.poetry]
name = "presign"
version = "0.1.0"
description = ""
authors = ["Aly <aly@sidi.ca>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
boto3 = "^1.26.81"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
